[package]
name = "pushit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openapi = { path = "ext/twilio-rust" }
tide = "0.16.0"
tokio = { version = "1.15.0", features = ["full"] }
